services:
  notes-frontend:
    image: ghcr.io/alexanderboldt/notes-frontend:1.0.0-local
    container_name: notes-frontend
    ports:
      - 4100:80
    networks:
      - notes

networks:
  notes:
    name: notes
    external: true
